project:
  type: book
  output-dir: docs

book:
  title: "데이터 분석을 위한 실무 R"
  author: "YK"
  date:  "`r Sys.Date()`"
  chapters:
    - index.qmd
    - identify.qmd
    - collect.qmd
    - clean.qmd
    - analyze.qmd
    - interpret.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo




