project:
  type: book
  output-dir: docs

book:
  title: "데이터분석 실무 R기"
  author: "YK"
  date: last-modified
  date-format: iso
  chapters:
    - index.qmd
    - identify.qmd
    - collect.qmd
    - clean.qmd
    - analyze.qmd
    - interpret.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    mermaid:
      theme: neutral

freeze: auto